services:
  dagster-webserver:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - DOCKER_DEFAULT_PLATFORM=linux/amd64
      - DAGSTER_HOME=/opt/dagster/dagster_home
    # execute bash command to keep the container running
    volumes:
      - ./dagster_home:/opt/dagster/dagster_home
    networks:
      - internal-dagster
  dagster-daemon:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: "dagster-daemon run"
    restart: unless-stopped
    environment:
      - DOCKER_DEFAULT_PLATFORM=linux/amd64
      - DAGSTER_HOME=/opt/dagster/dagster_home
    # execute bash command to keep the container running
    volumes:
      - ./dagster_home:/opt/dagster/dagster_home
    networks:
      - internal-dagster
  dagster-postgres:
    image: postgres:14
    # ports:
    #   - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-dagster}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-dagster}
    volumes:
      - dagster-postgres:/var/lib/postgresql/data
    networks:
      - internal-dagster
volumes:
  dagster-postgres:
    driver: local

networks:
  # web:
  #   external: true
  internal-dagster:
    external: false
    driver: bridge
