services:
  dagster-webserver:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 3000:3000
  dagster-daemon:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: "dagster-daemon run"
  dagster-postgres:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=gaster
    volumes:
      - dagster-postgres:/var/lib/postgresql/data
volumes:
  dagster-postgres:
    driver: local
